version: "3.8"
services:
   # MySQL database service

  db:
      image: msql
      container_name: database_docker_symfony
      restart: always
      volumes:
        - db-data:/var/lib/mysql
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      network: 
        - dev
  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin_docker_symfony
      restart: always
      depends_on:
        - db
      ports:
        - 8080:80
      environement:
        PMA_HOST: db
      network:
        - dev

networks:
    dev:

volumes:
    db-data:




